import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------------------
# This file is auto-generated by the notebook. Do not edit manually.
# Import ModelConfig from the notebook or define it here for standalone use.
# ----------------------------------------------------------------------
class ModelConfig:
    MODEL_TYPE = "LSTM_attention"
    LAYER_NORM_EMB = True
    FREEZE_TOKEN_EMBEDDING = True
    TOKEN_EMBEDDING = "gloVe-6B-100d"
    EMB_DIM = 100
    EMB_DP = 0.2
    BIDIRECTIONAL = True
    DROPOUT = 0.5
    FC_DIMS = (128,)
    FC_NON_LINEARITY = "GELU"
    HIDDEN_DIM = 256
    ATTENTION_DROPOUT = 0.0
    LAYER_NORM_LSTM = False
    LAYER_NORM_ATTENTION = False
    ATTENTION_PROJECTION = False
    PROJECT_DIM = 128
    MASK_FILL_NUM = -1e10
    SIAMESE_CONCAT = ["difference"]
    NUM_LAYERS = 2
    SKIP_CONNECTION = False
    USE_BILINEAR = False
model_cfg = ModelConfig()


class Attention(nn.Module):
    def __init__(self, hidden_dim, mask_fill_num=model_cfg.MASK_FILL_NUM, dropout=model_cfg.ATTENTION_DROPOUT):
        super(Attention, self).__init__()
        self.W = nn.Linear(hidden_dim, hidden_dim)
        self.V = nn.Linear(hidden_dim, 1, bias=False)
        self.mask_fill_num = mask_fill_num
        self.dropout = nn.Dropout(dropout)

    def forward(self, lstm_output, mask):
        energy = torch.tanh(self.W(lstm_output))
        scores = self.V(energy).squeeze(-1)
        scores = scores.masked_fill(mask == 0, self.mask_fill_num)
        weights = F.softmax(scores, dim=-1)
        weights = self.dropout(weights)
        lstm_masked = lstm_output * mask.unsqueeze(-1)
        weights = weights.unsqueeze(1)
        context = torch.bmm(weights, lstm_masked)
        return context.squeeze(1), weights


class QuoraSiameseClassifier(nn.Module):
    def __init__(self, vocab_size, config=model_cfg, embedding=None):
        super().__init__()
        self.config = config

        self.embedding = nn.Embedding(vocab_size, config.EMB_DIM)
        self.emb_norm = nn.LayerNorm(config.EMB_DIM)
        self.emb_dropout = nn.Dropout(config.EMB_DP)
        if embedding is not None:
            print("Glove copied in Embedding Layer...")
            self.embedding.weight.data.copy_(embedding)
            self.embedding.weight.requires_grad = not config.FREEZE_TOKEN_EMBEDDING

        self.LSTM = nn.LSTM(
            input_size=config.EMB_DIM,
            hidden_size=config.HIDDEN_DIM,
            bidirectional=config.BIDIRECTIONAL,
            num_layers=config.NUM_LAYERS,
            dropout=config.DROPOUT if config.NUM_LAYERS > 1 else 0.0,
            batch_first=True
        )
        lstm_output_dim = config.HIDDEN_DIM * (2 if config.BIDIRECTIONAL else 1)

        self.attention = Attention(lstm_output_dim)

        if config.ATTENTION_PROJECTION:
            self.proj = nn.Linear(lstm_output_dim, config.PROJECT_DIM)
            feature_dim = config.PROJECT_DIM
        else:
            self.proj = nn.Identity()
            feature_dim = lstm_output_dim

        self.use_bilinear = getattr(config, 'USE_BILINEAR', False)
        if self.use_bilinear:
            self.bilinear = nn.Bilinear(feature_dim, feature_dim, 1)
            fc_input_dim = feature_dim + 1
        else:
            fc_input_dim = feature_dim

        fc_layers = []
        in_dim = fc_input_dim
        for d in config.FC_DIMS:
            fc_layers += [nn.Linear(in_dim, d), nn.GELU(), nn.Dropout(config.DROPOUT)]
            in_dim = d
        fc_layers.append(nn.Linear(in_dim, 1))
        self.fc = nn.Sequential(*fc_layers)

    def _create_mask(self, question):
        return (question != 0).float()

    def _encode(self, question):
        emb = self.embedding(question)
        emb = self.emb_norm(emb)
        emb = self.emb_dropout(emb)
        mask = self._create_mask(question)
        out, _ = self.LSTM(emb)
        ctx, _ = self.attention(out, mask)
        return ctx

    def forward(self, q1, q2):
        h1_raw = self._encode(q1)
        h2_raw = self._encode(q2)

        h1 = self.proj(h1_raw)
        h2 = self.proj(h2_raw)

        diff = torch.abs(h1 - h2)

        if self.use_bilinear:
            bilinear_sim = self.bilinear(h1, h2)
            feat = torch.cat([diff, bilinear_sim], dim=1)
        else:
            feat = diff

        logits = self.fc(feat).squeeze(1)
        return logits
